### ISSUE TITLE
Issue with typescript definition

### ISSUE THREAD

**Issue by darewreck54** [microsoft/powerbi-visuals-utils-interactivityutils#27]
the index.d.ts needs to be updated to account for changes in types.

/node_modules/powerbi-visuals-utils-interactivityutils/lib/index.d.ts : (110,44) Generic type 'Selection<GElement, Datum, PElement, PDatum>' re
quires 4 type argument(s).
/node_modules/powerbi-visuals-utils-interactivityutils/lib/index.d.ts : (110,64) Generic type 'Selection<GElement, Datum, PElement, PDatum>' re
quires 4 type argument(s).
node_modules/powerbi-visuals-utils-interactivityutils/lib/index.d.ts : (231,62) Generic type 'Selection<GElement, Datum, PElement, PDatum>' re
quires 4 type argument(s).
node_modules/powerbi-visuals-utils-interactivityutils/lib/index.d.ts : (232,55) Generic type 'Selection<GElement, Datum, PElement, PDatum>' re
quires 4 type argument(s).
node_modules/powerbi-visuals-utils-svgutils/lib/index.d.ts : (342,33) Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 t
ype argument(s).

I had to add modifiy d3.Selection<any> to d3.Selection<any,any, any, any>.

This occurs when you use a different version of d3 version 4.13.  It seems that the this library is tied to a specific d3 version.  If you import other libraries that depend on higher version how would you account for this?

**Comment by uve** [comment]
try to import the following package:
https://www.npmjs.com/package/@types/d3-selection
