### ISSUE TITLE
Cannot make example of 'interactivityService' work

### ISSUE THREAD

**Issue by jsslngz** [microsoft/powerbi-visuals-utils-interactivityutils#53]
I'm trying to create a simple behavior for my custom visual, but i can't pass the example part.

`import ISelectionHandler = powerbi.extensibility.utils.interactivity.ISelectionHandler;
import SelectableDataPoint = powerbi.extensibility.utils.interactivity.SelectableDataPoint;
import IInteractiveBehavior = powerbi.extensibility.utils.interactivity.IInteractiveBehavior;

export interface YourBehaviorOptions {
    selection: d3.Selection<SelectableDataPoint>;
}

export class YourBehavior implements IInteractiveBehavior {
    // Implementation of IInteractiveBehavior

    public bindEvents(
        behaviorOptions: YourBehaviorOptions,
        selectionHandler: ISelectionHandler): void {

        const multiSelect: boolean = true;

        behaviorOptions.selection.on("click", (dataPoint: SelectableDataPoint) => {
            selectionHandler.handleSelection(subDataPoint, multiSelect); // Selects the dataPoint
        });
    }
}`

the error i'm recieving:

`error  TYPESCRIPT  /src/behaviors.ts : (9,14) Class 'YourBehavior' incorrectly implements interface 'IInteractiveBehavior'.
  Types of property 'bindEvents' are incompatible.
    Type '(behaviorOptions: YourBehaviorOptions, selectionHandler: ISelectionHandler) => void' is not assignable to type '(behaviorOptions: IBehaviorOptions<BaseDataPoint>, selectionHandler: ISelectionHandler) => void'.
      Types of parameters 'behaviorOptions' and 'behaviorOptions' are incompatible.
        Type 'IBehaviorOptions<BaseDataPoint>' is not assignable to type 'YourBehaviorOptions'.
          Property 'selection' is missing in type 'IBehaviorOptions<BaseDataPoint>'.
 error  TYPESCRIPT  /src/visual.ts : (277,45) 'ISelectionHandler' only refers to a type, but is being used as a value here.`

**Comment by helen508light** [comment]
@jsslngz is this issue still reproducable for you?
Which version of interactivity-utils had you been used?

If you use IInterctiveBehaviour, you need to specify this methods
```
export interface IInteractiveBehavior {
    bindEvents(behaviorOptions: IBehaviorOptions<BaseDataPoint>, selectionHandler: ISelectionHandler): void;
    renderSelection(hasSelection: boolean): void;
|
```

YourBehaviorOptions need to specify behavior and dataPoints, but they both are not presented in your source code
```
export interface IBehaviorOptions<SelectableDataPointType extends BaseDataPoint> {
    behavior: IInteractiveBehavior;
    dataPoints: SelectableDataPointType[];
    interactivityServiceOptions?: InteractivityServiceOptions;
}
```

**Comment by jsslngz** [comment]
Hi @helen508light, thank you for your reply. I'm not facing this issue anymore so I'm closing the issue.
