### ISSUE TITLE
Property 'applySelectionFilter' does not exist on type 'ISelectionHandler'

### ISSUE THREAD

**Issue by jamesabrook** [microsoft/powerbi-visuals-utils-interactivityutils#57]
I have a custom visual project that I've been working on which used the .applySelectionFilter() method to filter a table based on the name of an object that was clicked.  However, having updated to d3 v5 to take advantage of some of the newer features and after updating the version of interactivityutils I now get the error that applySelectionFilter doesn't exist.  Has it just been replaced with a different name or do I need to find a new way of filtering an existing visual from my custom visual?

Thanks,

**Comment by helen508light** [comment]
This method has been deleted from the new API. Now there are 3 types of filters https://microsoft.github.io/PowerBI-visuals/docs/concepts/filter-api/
Please try applyJsonFilter at first, may be it will be more suitable for your case.
But note, that new types of filters and old applySelectionFilter has differences in behavior.
In some cases it may be cause of bugs
```
carName | carMark
Corolla | Toyota
 Rav 4  | Toyota 
```

In some filtering cases only Corolla would be displayed for Toyota
