### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Hamzamusameh** [microsoft/powerbi-visuals-utils-interactivityutils#69]
Hi
After follow the installation instructions, the visuals generate this error:

![error](https://user-images.githubusercontent.com/40008971/79685844-5f828e00-8244-11ea-8d72-2f81ac9c29c8.PNG)

**Comment by helen508light** [comment]
@Hamzamusameh 
How do you use this repo and please give visual's a code that includes imports from current package

**Comment by Hamzamusameh** [comment]
@helen508light
I'm just install packages and added in both pbiviz file and tsconfig. 
Yes, please https://github.com/Hamzamusameh/Arrow-Chart.git

**Comment by helen508light** [comment]
@Hamzamusameh 
You are using API 2.6 and modern Power BI utils adopted for webpack
according to instruction https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/
you shouldn't write modules in pbiviz.json `externalJS` section, you should import it in your source code, also in tsconfig you should use only visual.ts in `files` section. Also, don't use `dependencies: null`
Please do not mix old and new way of writing visuals
